Fix deprecated warning in CachingReflector.php
brightnucleus/injector pull request #4
Opened 2021-07-20 15:07 UTC by svenvonarx

This change will fix a deprecated warning showing up in PHP Version >= 8.0

2021-10-27 12:15 UTC, svenvonarx commented
Any updates possible on this one?

2021-10-27 12:24 UTC, schlessera commented
The fix breaks on PHP versions lower than 7, as `$param->getType()` was only introduced with PHP 7.

Given that this package was initially targeting PHP 5.2+, we shouldn't break that expectation if it can be helped.

Are you up for adapting the PR so that it checks the PHP version and does the proper logic based on that? For an example of how this can be done, you can see https://github.com/ampproject/amp-wp/blob/77ff4c482267e7ef6922215239d02675081b59d5/src/Infrastructure/Injector/SimpleInjector.php#L316-L355

2021-10-27 12:27 UTC, svenvonarx commented
Thank you very much for your fast response, I will try to adapt it today during afternoon.

2021-10-28 16:35 UTC, svenvonarx commented
Wasn't able to do it yesterday but now i hopefully adjusted it by the way we want it.

2021-11-05 13:30 UTC, schlessera requested changes

2021-11-05 13:30 UTC, schlessera commented on src/CachingReflector.php
> +			// support it.
```suggestion
            // As $parameter->(has|get)Type() was only introduced with PHP 7.0+,
            // we need to provide a work-around for PHP 5.6 while we officially
            // support it.
```

2021-11-05 13:30 UTC, schlessera commented on src/CachingReflector.php
> +        if ( PHP_VERSION_ID >= 70000 ) {
```suggestion
        if (PHP_VERSION_ID >= 70000) {
```

2021-11-05 17:01 UTC, svenvonarx commented
Should be resolved, thanks for the prepared changes!

2021-11-29 10:44 UTC, svenvonarx commented
Are there any more changes needed from my side? :)

2021-11-29 13:19 UTC, schlessera approved these changes

2021-11-29 13:20 UTC, merged